### ISSUE TITLE
Add support for multiple="multiple" on select elements?

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/o-forms#100]
I recently ended up using a `<select multiple="multiple" ... >` for a form, because I feel they do have a use in interfaces - where the primary use case is selecting a single value, but you do want to be able to select multiple values, they do offer something that neither checkboxes or radio buttons quite satisfy.

Unfortunately, this doesn't work with the current o-forms because `<select>` elements have a height of `36px` set.  I temporarily fudged around this by outputting a height based on base padding + (option count * option height).

Styling multiple selects is... hard though.  I don't know what choices there are for that :)  http://www.456bereastreet.com/lab/styling-form-controls-revisited/select-multiple-option/

Thoughts?

**Comment by kaelig** [comment]
This looks very much like an edge case that could easily be tweaked by products for their needs.

Feel free to provide a PR or share your code here for future reference.

**Comment by onishiweb** [comment]
Would it be worth looking into support for a `multiple` select style, or as Kaelig says allow products to work around this. I think if it's possible to use a select as a multi-select, we should probably aim to support it and not let the element break...

**Comment by onishiweb** [comment]
In v3 this does look a bit dodgy. Looking into supporting this now.
