### ISSUE TITLE
Component is not using proper BEM classes

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-forms#109]
This was turned up while updating tests in the build tool. A lot of the classes aren't BEM. E.g. `.o-forms-label` should be `.o-forms__label`.

**Comment by jamesnicholls** [comment]
This is the way it used to be named. I think the rationale for the change was because `.o-forms` is not a block, it is the root namespace for the module. It's been awhile since I looked at o-forms though. Things may have changed.

**Comment by AlbertoElias** [comment]
I think that for consistency, we should still move to a more BEMy class naming style, and maybe call `o-forms-group` just `o-forms` and make that the block
