### ISSUE TITLE
Select list items in a loop in Windows Mobile

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/o-forms#111]
List items in form are in a loop in Windows IE Mobile browser. 

Video capture: https://subscription.ft.com/?segid=70000&countryCode=GBR&offerId=713f1e28-0bc5-8261-f1e6-eebab6f7600e

Tested against: Windows 10 phone (issue may be present in other Windows mobile OS versions)
Issue appears in current Subscription app (https://subscription.ft.com/?segid=70000&countryCode=GBR&offerId=713f1e28-0bc5-8261-f1e6-eebab6f7600e) and in the Next signup form (which is still being developed).

**Comment by Riyanat** [comment]
This is a general issue. In Windows 10 phones, list items that overflow are wrapped hence they appear like they are in an infinite loop. This may be the expected behaviour.
