### ISSUE TITLE
Add validity checking

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-forms#125]
Things like https://github.com/Financial-Times/system-registry/pull/6#issuecomment-257518808 include their own very generic validity checking. This would be a useful function to add to o-forms.

**Comment by onishiweb** [comment]
Added in #135

**Comment by lucas42** [comment]
@GeoffThorpeFT it'd be worth trying out o-forms v3.3.0 at some point - it should allow you to get of that hacky validation code I wrote.
