### ISSUE TITLE
Add small versions of items

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-forms#130]
There are usecases where it is useful, like forms within elements.
AV has a curation tool for editors, which is using forms o o-cards:
![image](https://cloud.githubusercontent.com/assets/4048999/20145148/a80fcfb0-a6a7-11e6-9ec4-86a60def186f.png)
This is how it looks with v2 small form items, unfortunately normal size v3 items cannot be used, they are just too big.

**Comment by onishiweb** [comment]
Hi @roland-vachter, we'll add this back in next week. Will have a look in v2 and confirm the modifier that was being used and make sure it maps to the same one as before as well.
