### ISSUE TITLE
Documentation: more detail about what 'common fields' means

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-forms#151]
e.g., in the sass docs 
![image](https://user-images.githubusercontent.com/447559/28020900-dd37ef52-657d-11e7-8b83-b3c0711d3b6e.png)

I'm _guessing_ this means text inputs + textarea, but can't find anything telling me if that's right

**Comment by wheresrhys** [comment]
As an addendum, I eventually found the `oFromsTextarea` mixin, but this has some dependency on the common styles, which is kinda obvious i suppose, but coudl be more so

**Comment by notlee** [comment]
@wheresrhys This has been improved in v5 of o-fors. Thanks for the feedback :D 

<img width="888" alt="screen shot 2018-01-31 at 13 43 09" src="https://user-images.githubusercontent.com/10405691/35626220-e7e6d048-068c-11e8-9132-40851257af9d.png">
<img width="1403" alt="screen shot 2018-01-31 at 13 44 03" src="https://user-images.githubusercontent.com/10405691/35626236-f89bcd58-068c-11e8-9871-af2f29ffdb75.png">
