### ISSUE TITLE
 o-forms v2 update

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-forms#160]
**Have updated the main component sketch file (here: https://drive.google.com/open?id=0B8f0KVx7ey79NlNwREpXSjJKV28)** 

_A few updates to the overall o-forms and new updated designs for Prefix-Suffix field types (more aligned with the other changes we made as part of NEXT)._ 

- [x] This includes increasing field height from 38px to 40px. This then ensures the associated buttons can be the default secondary larger buttons and align perfectly. 

- [ ] To add space between the associated check boxes and buttons to aid with touch targets on mobile. 

- [ ] Increase the smaller text to 16px across o-forms. 

- [ ] Increase the vertical space between individual fields to 20px and decrease the space between field title and entry box to 8px. This is to make it easier to see which title is attached to which entry box. 

- [x] Closing up the gap between radios and checkboxes and the associated text from 16px to 12px. This helps with then they are displayed as a vertical list on smaller breakpoints and makes it easier to know what text it is linked to. 

- [ ] To reduce the (subsequent) paragraph space on Checkboxes With Long Text to neaten up how this looks when there are a number of permissions (something that may come up more with GDPR). 

- [x] To add an optional label to any field titles so we don’t have to mark all required fields with asterisks.

**Comment by notlee** [comment]
Updates have been released in v5 https://github.com/Financial-Times/o-forms/pull/180
