### ISSUE TITLE
Some fields aren't displaying correctly. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-forms#161]
Some of the alignments have gone awry for the following fields:

<img width="386" alt="screen shot 2017-10-06 at 12 36 29" src="https://user-images.githubusercontent.com/11214093/31276356-5065c9f4-aa93-11e7-81fc-b690525d85c5.png">
<img width="511" alt="screen shot 2017-10-06 at 12 36 35" src="https://user-images.githubusercontent.com/11214093/31276357-524c7b14-aa93-11e7-82a8-7b97a85f7500.png">

**Comment by notlee** [comment]
Thanks @draysonandstock, looks like I might have introduced this issue with the addition of checkbox toggles for `o-forms@4.1.0`. I'll look into it today.

**Comment by notlee** [comment]
This is corrected in [v4.1.2](https://github.com/Financial-Times/o-forms/releases/tag/v4.1.2)
