### ISSUE TITLE
Update to focus states on o-forms

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-forms#195]
We are currently inconsistent in how we handle the focus state on o-form fields. To align more with o-buttons we could keep the normal 1px outline and run the 2px bright teal border outside of this on focus. This would need to be the case for any valid or invalid fields also. 

This ensures the underlying page/form structure isn't obscured when any elements are in focus. 

**Current example:**
![screen shot 2018-03-21 at 09 39 08](https://user-images.githubusercontent.com/11214093/37702859-c98f339e-2ceb-11e8-8e63-b29bfe0932d8.png)

**Proposed changes (also in the o-forms sketch file):**
![screen shot 2018-03-21 at 09 39 57](https://user-images.githubusercontent.com/11214093/37702908-ebeddd1e-2ceb-11e8-81d7-f8a8d7f01649.png)

**Comment by notlee** [comment]
Released in https://github.com/Financial-Times/o-forms/releases/tag/v5.2.4 👍
