### ISSUE TITLE
Select valid styles override disabled styles

### ISSUE THREAD

**Issue by liamkeaton** [Financial-Times/o-forms#197]
`.o-forms--valid .o-forms__select` overrides `.o-forms__select:disabled` styles making a disabled select box still look active.

<img width="475" alt="screen shot 2018-03-23 at 10 00 06" src="https://user-images.githubusercontent.com/1721150/37823298-00a6fc40-2e81-11e8-9219-96f00b6cd390.png">

**Comment by notlee** [comment]
Released in https://github.com/Financial-Times/o-forms/releases/tag/v5.2.4 :)
