### ISSUE TITLE
Label - allow normal font weight

### ISSUE THREAD

**Issue by jonnywyatt** [Financial-Times/o-forms#213]
eg styled 'yes/no' radio button labels aren't bold. Add a o-forms__label--normal-weight (terrible name sorry but you get the idea) variant?
@draysonandstock fyi

![image](https://user-images.githubusercontent.com/471250/39360322-b6a26d86-4a15-11e8-9e4e-f62ca9395697.png)

**Comment by notlee** [comment]
@draysonandstock @jonnywyatt Does the removal of bold labels apply to inline controls, and only inline controls? We have a modifying class for inline controls so we could override label font weight there.

**Comment by gvonkoss** [comment]
There hasn't been any new development on this, but we can add it at a later date should the request come up again.
