### ISSUE TITLE
Saved feedback - pushes following content downwards

### ISSUE THREAD

**Issue by jonnywyatt** [Financial-Times/o-forms#219]
When the saving / saved label appears, could it occupy the existing space and not alter the height of the whole Yes / No block? Then it won't push any following content downwards.

**Comment by draysonandstock** [comment]
![wheat box position 1](https://user-images.githubusercontent.com/11214093/40652904-8a48c4a8-6331-11e8-8c2b-d6397a707ca9.png)
![wheat box position 2 has shifted by the height of the feedback message](https://user-images.githubusercontent.com/11214093/40652905-8a5e2848-6331-11e8-9d29-335ae329ca94.png)

**Comment by notlee** [comment]
Addressed in [v5.7.2](https://github.com/Financial-Times/o-typography/releases/tag/v5.7.2)
