### ISSUE TITLE
Handle hidden "styled radio buttons"

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-forms#242]
The right border is applied to the last child of styled radio buttons rather than the container. This means if the last radio button is set to `display: none` no right border is visible
<img width="437" alt="screenshot 2019-02-05 at 13 32 36" src="https://user-images.githubusercontent.com/10405691/52278496-1734c400-294f-11e9-9de8-3e25a3f9283a.png">

This is a problem on the FT payment page for example, where payment options are hidden until the browser confirms support (i.e. Apply Pay).

More context: https://financialtimes.slack.com/archives/C02FU5ARJ/p1549374296124400

**Comment by notlee** [comment]
☝️@gvonkoss Does the new major handle this case? I bet it does because it's so much less messy.

**Comment by gvonkoss** [comment]
Yes it does! ✨

**Comment by notlee** [comment]
Cool!
