### ISSUE TITLE
optional vs required form elements

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-forms#249]
Currently, `o-forms` provides the ability to mark an input element as 'optional':

<img width="406" alt="Screenshot 2019-03-27 at 15 19 11" src="https://user-images.githubusercontent.com/16777943/55088491-b8184380-50a3-11e9-8abe-8b3c5755cf58.png">

The current thought is that it makes more sense (based on most other form UIs and semantic HTML) to make this 'required' instead. e.g.

<img width="536" alt="Screenshot 2019-03-27 at 15 20 24" src="https://user-images.githubusercontent.com/16777943/55088569-dda54d00-50a3-11e9-9ff7-4587f3d0c1ae.png">

Stylistically there may not be much difference, but there is  the question of how we implement forms and what the user experience perspective on this is—any thoughts?

**Comment by notlee** [comment]
For reference, James went for this as typically we have more required fields than optional: 
https://github.com/Financial-Times/o-forms/issues/150#issuecomment-334729506

**Comment by gvonkoss** [comment]
We've agreed to make required the default, and point out when a form element is required.
