### ISSUE TITLE
Checkbox pseudo element positions are not calculated correctly

### ISSUE THREAD

**Issue by bbcreatv** [Financial-Times/o-forms#285]
## What

[Bug]: On mobile widths the checkbox pseudo element positions are not calculated correctly - with no modifications to css. On the origami demo page it seems to be happening to the right side checkbox only.

![Screenshot 2019-09-02_22-40-58-161](https://user-images.githubusercontent.com/3500928/64132830-c563f780-cdd2-11e9-9109-27dbdf2259d7.png)

## Details
- Chrome 76
- iPhone X/Desktop
- o-forms v7.0.11
![Screenshot 2019-09-02_22-31-48-886](https://user-images.githubusercontent.com/3500928/64132732-2808c380-cdd2-11e9-96d6-238257b4e0b7.png)

**Comment by notlee** [comment]
Looks like we missed this issue! Thanks for making it detailed 😊 
I've opened a PR with a fix: https://github.com/Financial-Times/o-forms/pull/307

**Comment by notlee** [comment]
A fix was released in v8.1.5
