### ISSUE TITLE
Date input DD regex currently accepts any two digit number up to 99

### ISSUE THREAD

**Issue by AniaMakes** [Financial-Times/o-forms#317]
Current behaviour: DD accepts numbers up to 99 as correct (based on regex [0-9]{2})

Desired behaviour: DD rejects anything over 31. Suggested regex pattern: `(0[1-9]|[12]\d|3[01])` (per [this thread](https://stackoverflow.com/questions/6076979/regular-expression-to-match-a-valid-day-in-a-date)) however trying this breaks the looks which I think relies on _pattern ends in {2}_ and would need update in CSS to match.

(Whilst this is far from full client validation, this would help)

**Comment by chee** [comment]
i reckon we should add this better regex to the css like `&[pattern='(0[1-9]|[12]\d|3[01])'],` [here](https://github.com/Financial-Times/o-forms/blob/master/src/scss/_date.scss#L23-L25), and add a the demo that uses it.
we can leave the current one there and maybe deprecate it, and revisit how [this whole thing](https://github.com/Financial-Times/o-forms/blob/master/src/scss/_date.scss#L19-L34) works in the next major version
