### ISSUE TITLE
Bug: radio buttons and checkboxes in Windows 10 high contrast mode

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-forms#320]
## What

In Windows 10 high contrast mode, there's an issue with radio buttons and checkboxes. Because we use `background-color` to indicate selected state, and high contrast mode overrides all the background colours, we lose selected state. See the [DAC issue reported on FT.com here](https://trello.com/c/AQUdnOWz/165-content-not-visible-in-high-contrast-issue-id-dachighcontrast01).

## Potential solutions

1. See if we can replicate the existing behaviour in high contrast mode, using a media query to override default high contrast styles. This may be difficult as certain CSS properties seem to be unchangeable in high contrast mode

2. In high contrast mode, use a media query to remove all custom radio button and checkbox styles, reverting to the OS default

## Additional information

This work _may_ not fix the reported DAC issue by itself, and work may need to be done in the specific application where the issue is present. We'll work with Customer Products Ops Cops to hand over this work if we need to.

**Comment by notlee** [comment]
o-forms already handles high contrast mode.
<img width="514" alt="Screenshot 2020-02-28 at 14 23 25 1" src="https://user-images.githubusercontent.com/10405691/75556330-ec278180-5a35-11ea-954c-49d4d4747ea4.png">

We use a media query to reset the background colour of the radio box in high contrast mode.
```
@media screen and (-ms-high-contrast: active) {
    background-color: windowText;
}
```
https://github.com/Financial-Times/o-forms/blob/869240cd0e199de9f6a88a6c5abae1ca89158c14/src/scss/_radio-round.scss#L33

And thus its fixed on ft.com
<img width="511" alt="Screenshot 2020-02-28 at 14 35 25" src="https://user-images.githubusercontent.com/10405691/75557266-9d7ae700-5a37-11ea-972a-17dca5198605.png">

**Comment by notlee** [comment]
It was fixed two years ago? https://github.com/Financial-Times/o-forms/pull/200/files#diff-12b0210cae4dd2ece978ad72b68c87c2R20
