### ISSUE TITLE
input[disabled] text and background is faded on iOS

### ISSUE THREAD

**Issue by tolujimoh** [Financial-Times/o-forms#347]
Safari, Firefox, and Chrome browsers on iOS are rending `disabled` input fields with an opacity of `0.4` This causes the input text and background colors to fade out.

###  Current view
![IMG_8235](https://user-images.githubusercontent.com/17183724/83532811-aec80980-a4e6-11ea-8c7f-890c2dcc3ce1.jpg)

###  Expected view
![IMG_8236](https://user-images.githubusercontent.com/17183724/83533011-f3ec3b80-a4e6-11ea-9245-141eb52703b0.jpg)

**Comment by JakeChampion** [comment]
@tolujimoh I don't see this on Firefox Stable or Chrome Stable. Could you please post which versions of the browsers you are seeing this on?

The page I tested on is https://www.ft.com/__origami/service/build/v2/demos/o-forms@8.3.6/text-input?brand=master

Here is Chrome 83 and the devtools open to show the opacity is at 1
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1569131/83534958-6231fd80-a4e9-11ea-90cc-600d798a7f1d.png">


Here is Firefox 76 and the devtools open to show the opacity is at 1
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1569131/83535079-8261bc80-a4e9-11ea-9f0a-83718d4514aa.png">

**Comment by JakeChampion** [comment]
Here is Firefox 77, it also looks to have the correct opacity of 1
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1569131/83535309-bfc64a00-a4e9-11ea-8995-60b7505f34d1.png">

**Comment by tolujimoh** [comment]
@JakeChampion The input element displays correctly on web browsers, however, the bug exists on IOS devices. 

My Safari version is Safari 13, Chrome version is Chrome 83, and Firefox version is Firefox for iOS 26

![IMG_829F96284264-1](https://user-images.githubusercontent.com/17183724/83539614-2863f580-a4ef-11ea-8dfb-6cdc8ac177a4.jpeg)

<img width="786" alt="Screenshot 2020-06-02 at 16 33 37" src="https://user-images.githubusercontent.com/17183724/83539380-dcb14c00-a4ee-11ea-9bce-1aeeb1c0c33d.png">

**Comment by JakeChampion** [comment]
This was fixed in v8.3.7 of o-forms :-) Thanks for the issue @tolujimoh
