### ISSUE TITLE
Transparent radio buttons can make them look inactive

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-forms#389]
2 people have made the mistake that these radio buttons are inactive because they are on a grey background:

![image](https://user-images.githubusercontent.com/447559/109701225-afcbbb80-7b8a-11eb-974c-c2d11aa2ac03.png)

No other inputs (except perhaps checkboxes) "inherit" the background colour from the container, so this behaviour is surprising and confusing for users.

**Comment by wheresrhys** [comment]
`background-color: white;` on the `::before` pseudo element appears to fix it, though there may be some undesirable side effects

**Comment by notlee** [comment]
Yeah adding a white background for the internal brand seems sensible. We can leave the master brand unaffected so it continues to look the same on paper/white backgrounds. I'll pass this by the design team
