### ISSUE TITLE
more realistic examples

### ISSUE THREAD

**Issue by tomgp** [Financial-Times/o-forms#42]
Where possible we should try to make the examples reflect the real world usage. In order meet the goal of being a 'living style guide' we should provide users guidance about the why and wherefores of use as well as being a catalogue of components. 

Some examples...

Within an FT context would we ever have a "http://" prefix on a form field left alone a ".com" ? 

Under what circumstances would we prefer a button prefixed to a text field as opposed to a generic button after it?

"Invalid entry" is a poor error message, telling the user nothing about how to correct their mistake we should "Please enter a valid url" is better but again, where would we expect an FT user to enter a URL protocol?

I suppose these are really a combination of providing some supporting text and making the examples more focused on real world requirements.

the [gov.uk style guide](http://govuk-elements.herokuapp.com/#guide-forms) is excellent in this respect for example the check boxes section:
"use these to select either on/off toggles or multiple selections
make it clear with words when users can select one or multiple options"
accompanied by a believable example instead of generic "option 1", "option 2" type filler.

**Comment by kaelig** [comment]
@tomgp what do you think of this demo of a real-life form: build.origami.ft.com/files/o-forms@1.0.0-beta.9/demos/real-life.html ?

Would that be a good compromise? Also happy to add more "realistic" demos that are better suited for interactives.

**Comment by kaelig** [comment]
I'll then take that as a yes. Feel free to open PRs to add demos.

**Comment by callumlocke** [comment]
I missed your last comment before. That 'realistic' form example is great.

**Comment by pauloneillft** [comment]
@callumlocke btw that form has been in existence live for over a year

**Comment by kaelig** [comment]
@pauloneillft I think what was asked is to have demos of real life examples in the component itself.

**Comment by pauloneillft** [comment]
@kaelig ah right. cool then...
