### ISSUE TITLE
Disabled fields look a lot like buttons

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-forms#73]
Fields look like this when disabled:

![screenshot 2014-12-04 18 50 42](https://cloud.githubusercontent.com/assets/85783/5304006/7ef9bba6-7be6-11e4-99f7-7724e771efdb.png)

Should we have a look at making them look more 'disabled' and less emphasized on?

**Comment by kaelig** [comment]
I've played around with opacities, and here's my proposal:

![screen shot 2015-02-13 at 15 00 50](https://cloud.githubusercontent.com/assets/85783/6189270/3d43c55c-b391-11e4-851a-96ee1f315330.png)

### Colors
Text: default field background (30%) + default text (70%)
Border: default field background (50%) + default border (50%)
Background: default field background (15%) + default border (85%)

**Q: Why not RGBA (transparent colors)?** A: because plain colours are compatible with older browsers.

**Q: Why mixing colours instead of creating new use cases?** A: to avoid having to override lots of use cases in their code if a product wants to change the color scheme

#### Next to a normal field, for contrast:
![screen shot 2015-02-13 at 15 00 59](https://cloud.githubusercontent.com/assets/85783/6189272/3ee47884-b391-11e4-8eb5-e33e8c93281b.png)
![screen shot 2015-02-13 at 15 00 50](https://cloud.githubusercontent.com/assets/85783/6189270/3d43c55c-b391-11e4-851a-96ee1f315330.png)

**Comment by AlbertoElias** [comment]
:+1:

**Comment by kaelig** [comment]
For radio buttons and checkboxes it's a lot easier to code disabled states by just changing the opacity (down to 40%), here's what it looks like:

![screen shot 2015-02-13 at 15 25 11](https://cloud.githubusercontent.com/assets/85783/6189879/0369e1b8-b396-11e4-9a4e-217dff1d0d69.png)

![screen shot 2015-02-13 at 15 24 41](https://cloud.githubusercontent.com/assets/85783/6189880/05b3d08c-b396-11e4-9d19-d1d04db86ef5.png)

**Comment by kaelig** [comment]
Fixed in v1.
