### ISSUE TITLE
Using o-ft-forms in silent mode

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-forms#81]
I'm currently trying to use forms in silent mode. I understand silent mode is meant to require a little more work than non-silent mode but I think it's currently too cumbersome. For example, to use all radio button styles, you need to extend the base field placeholder, radio button placeholder, radio button label placeholder, radio button border placeholder and placeholders for the various states a radio button can be in.

It would be nice if you could simply include the features that you need (e.g. text inputs, selects, radio buttons) and receive all relevant styles, while excluding features that you don't (e.g. textareas, affixes).

**Comment by jamesnicholls** [comment]
I would like to see this addressed for milestone 1.0.0 as I assume it would require a breaking change.

**Comment by kaelig** [comment]
Thanks for the feedback, makes total sense. I've assigned it to the 1.0.0 milestone. (another reason for which this module needs a full rewrite!)

**Comment by kaelig** [comment]
We have discussed this and the v1 makes it easier to specify what you want to include with helper mixins.
