### ISSUE TITLE
Add a 'roundness' parameter

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-forms#97]
Next FT changes the roundness of buttons and forms, so to ease the transition to new styles we could have a configurable option.

**Comment by onishiweb** [comment]
I think it might just be worth making the designs for `o-forms` consistent with `o-buttons` as standard and letting Next continue to do their tweaks as they prefer? @AlbertoElias

**Comment by AlbertoElias** [comment]
Yeah, and their current designs aren't the same as they were a year ago. I think we can close this issue

**Comment by onishiweb** [comment]
👍
